### ISSUE TITLE
errorbar example

### ISSUE THREAD

**Issue by atredennick** [atredennick/esa_data_viz_2015#1]
Add a means with errorbar example and exercise to the presentation.

**Comment by atredennick** [comment]
Done, see commit cc56d12.

**Comment by atredennick** [comment]
@naupaka I added this example (which is admittedly difficult, but will bring together a lot of what people will have learned) on page 62 (exercise 5 in Section 12). Do you think it is a good location? And, does the code snippet give enough clues for how to make the plot (with a little nudging from the speaker too)?

Here is the page from the PDF:

![screen shot 2015-08-02 at 12 29 50 pm](https://cloud.githubusercontent.com/assets/2903862/9027011/3a777b64-3912-11e5-8b57-37c5b1217b02.png)

**Comment by naupaka** [comment]
I do agree that this is pretty challenging... but I agree is it something people will want to know how to do. I get nervous that we will not have introduced all these functions (`subset()`, `%in%`, `ddply()`). But I guess that is why you give it to them, then they use `ggplot()` to make the plot? What if you used `sepal` instead of `diamonds` for this exercise? Then you wouldn't need the `subset()` steps at the top and it would be less new all at once at the end of the workshop.

**Comment by naupaka** [comment]
I think the location is good - could even go a few slides earlier (maybe above exercise 4?) since I agree it would be great to get to, even if it means we don't get to the other examples immediately preceding it. Exercise 3 is meant to follow from the preceding slides about binning and being careful with bar plots.

**Comment by atredennick** [comment]
I'll move it up above Exercise 4. Yeah, I was worried about the lines of data wrangling too. The problem with the `iris` dataset is that it only has one factor, and we need two to make the common factorial ANOVA plot. I'm not very familiar with the canned datasets in R; are there others that we could use that I don't know of? One with two factors? An alternative is to forego the double factor and just plot means +/- sds by species from a single variable. Then say, "there is a factorial example up on the web" (which there is). This avoids subsetting and dodging, but maintains the `ddply` step, which I think is important to show.

**Comment by atredennick** [comment]
OK, I decided to just plot along a single factor on the x-axis so that it doesn't get too confusing. We can reference the two factor example (grazingXnitrogen) in the examples script. I also like this new setup (below) because if will force a bit of thinking through using the help (`?geom_errorbar()`) to get the answer. The colors are, of course, redundant, but I just wanted people to have use a couple commands.

![screen shot 2015-08-04 at 8 12 44 am](https://cloud.githubusercontent.com/assets/2903862/9060346/d4a1fb0a-3a80-11e5-8f82-ad2e037d3bdf.png)

**Comment by naupaka** [comment]
I like this better. Simpler, and less new stuff all at once. +1 to close.

Alternatively, there is a more "`ggplot`-native" way to do it on-the-fly:

``` r
ggplot(iris, aes(Species, Petal.Length, color = Species)) + 
    stat_summary(fun.y = mean, geom = "point", size = 3) + 
    stat_summary(fun.data = mean_sdl, geom = "errorbar", mult = 1, width = 0.2)
```

What do you think?  ddply is more generally flexible in this case, but we also will have covered the "stats" terminology earlier and this might be a way to practice that. I think it depends on how much detail we decide to go into with `plyr` earlier in the session. Usually it's a pretty quick overview before we move on.

The only non-intuitive bit in the `stat_summary()` approach is is the `mean_sdl()` helper function (which, while built into `ggplot`, is ported from `Hmisc`, and calculates the mean and standard deviations. But any function could go in there as needed... The real danger with this approach is that if someone asks how to add SE bars instead of SD, the answer is complicated because you have to make your own function (there's no built-in easy option for that), whereas that is easy enough to swap in with the `ddply()` approach you used.

``` r
ddply(iris, .(Species), summarise,
      mean.petal.length = mean(Petal.Length),
      se.petal.length = sd(Petal.Length)/sqrt(length(iris$Petal.Length)))
```

I really fine either way, though, and I like it how it is now too.

**Comment by atredennick** [comment]
I think I'll leave it as it is now (using `ddply`) since, as you mention, it is a little more flexible even if less ggplot-ty. Also, whenever I plot means and some kind of error, I usually want to know what those values are -- easier to just get it beforehand using `ddply` and then dropping those into `geom_point` or `geom_bar`. 

I think we're good to go! Thanks!
